services:
  - type: web
    name: instantbrand-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: FAL_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://your-vercel-frontend.vercel.app,http://localhost:3000
    healthCheckPath: /health
    autoDeploy: false